package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/tabwriter"

	"github.com/charmbracelet/huh"
	"github.com/spf13/cobra"
)

var projectCmd = &cobra.Command{
	Use:     "project",
	Aliases: []string{"nest"},
	Short:   "Manage project-level configuration",
}

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Initialize a local Owl project in the current directory",
	Run:   runProjectInit,
}

func runProjectInit(cmd *cobra.Command, args []string) {
	owlDir := ".owl"
	projectFile := filepath.Join(owlDir, "project.json")

	if _, err := os.Stat(projectFile); err == nil {
		fmt.Println("Owl project already initialized in this directory.")
		fmt.Printf("Project file: %s\n", projectFile)
		return
	}

	if err := os.MkdirAll(owlDir, 0755); err != nil {
		fmt.Println("Error creating project directory:", err)
		os.Exit(1)
	}

	templatesDir := filepath.Join(owlDir, "templates")
	if err := os.MkdirAll(templatesDir, 0755); err != nil {
		fmt.Println("Error creating templates directory:", err)
		os.Exit(1)
	}

	projectData := fmt.Sprintf(`{
  "version": "1.0",
  "created_at": "%s",
  "context": "",
  "guardrails": []
}
`, "2026-04-05")

	if err := os.WriteFile(projectFile, []byte(projectData), 0644); err != nil {
		fmt.Println("Error creating project file:", err)
		os.Exit(1)
	}

	fmt.Println("✓ Owl project initialized")
	fmt.Printf("  Project directory: %s\n", owlDir)
	fmt.Printf("  Project file: %s\n", projectFile)
	fmt.Printf("  Templates directory: %s/\n", templatesDir)
}

var projectAgentsCmd = &cobra.Command{
	Use:   "agents",
	Short: "Describe agent functionality and create AGENTS.md for the project",
	Run:   runAgentsCmd,
}

func runAgentsCmd(cmd *cobra.Command, args []string) {
	owlDir := ".owl"
	agentsFile := filepath.Join(owlDir, "AGENTS.md")

	if _, err := os.Stat(filepath.Join(owlDir, "project.json")); os.IsNotExist(err) {
		fmt.Println("Error: Owl project not initialized. Run 'owl project init' first.")
		os.Exit(1)
	}

	var name, role, capabilities, workflow string

	form := huh.NewForm(
		huh.NewGroup(
			huh.NewInput().
				Title("Agent Name").
				Description("What should we call this agent?").
				Value(&name),
		),
		huh.NewGroup(
			huh.NewInput().
				Title("Role").
				Description("What is this agent's primary role?").
				Value(&role),
		),
		huh.NewGroup(
			huh.NewText().
				Title("Capabilities").
				Description("What can this agent do? (one capability per line)").
				Value(&capabilities),
		),
		huh.NewGroup(
			huh.NewText().
				Title("Workflow").
				Description("Describe the typical workflow this agent follows.").
				Value(&workflow),
		),
	)

	if err := form.WithTheme(huh.ThemeCatppuccin()).Run(); err != nil {
		fmt.Println("Error running agents wizard:", err)
		os.Exit(1)
	}

	capList := strings.Split(strings.TrimSpace(capabilities), "\n")
	capBullets := ""
	for _, c := range capList {
		c = strings.TrimSpace(c)
		if c != "" {
			capBullets += fmt.Sprintf("- %s\n", c)
		}
	}

	agentsContent := fmt.Sprintf(`# %s

## Role
%s

## Capabilities
%s## Workflow
%s

---
*Auto-generated by 'owl project agents'. Edit to customize.*
`, name, role, capBullets, workflow)

	if err := os.WriteFile(agentsFile, []byte(agentsContent), 0644); err != nil {
		fmt.Println("Error writing AGENTS.md:", err)
		os.Exit(1)
	}

	fmt.Printf("\n✓ Agent description saved to %s\n", agentsFile)
}

var guardsCmd = &cobra.Command{
	Use:   "guards",
	Short: "Interview-based guardrail generator for the project",
	Run:   runGuardsCmd,
}

func runGuardsCmd(cmd *cobra.Command, args []string) {
	owlDir := ".owl"
	projectFile := filepath.Join(owlDir, "project.json")

	if _, err := os.Stat(projectFile); os.IsNotExist(err) {
		fmt.Println("Error: Owl project not initialized. Run 'owl project init' first.")
		os.Exit(1)
	}

	var hasGit bool
	if _, err := os.Stat(".git"); err == nil {
		hasGit = true
	}

	var guards strings.Builder
	guards.WriteString("# Project Guardrails\n\n")
	guards.WriteString("These guardrails define constraints that all agents working on this project must respect.\n\n")

	var guardrailList []string

	var confirmGuardrails bool

	form := huh.NewForm(
		huh.NewGroup(
			huh.NewConfirm().
				Title("Production Access").
				Description("Can agents push directly to production?").
				Value(&confirmGuardrails),
		),
	)

	if err := form.WithTheme(huh.ThemeCatppuccin()).Run(); err != nil {
		fmt.Println("Error running guards wizard:", err)
		os.Exit(1)
	}

	if !confirmGuardrails {
		guards.WriteString("## Production\n")
		guards.WriteString("- **NEVER** push directly to production branches\n")
		guards.WriteString("- **NEVER** modify production configuration without explicit approval\n")
		guards.WriteString("- **ALWAYS** route production changes through the standard review process\n\n")
		guardrailList = append(guardrailList,
			"NEVER push directly to production branches",
			"NEVER modify production configuration without explicit approval",
			"ALWAYS route production changes through the standard review process")
	}

	if hasGit {
		guards.WriteString("## Version Control\n")
		guards.WriteString("- Commit messages must be descriptive and follow conventional commits format\n")
		guards.WriteString("- **NEVER** force push to shared branches\n")
		guards.WriteString("- Create feature branches for all non-trivial changes\n\n")
		guardrailList = append(guardrailList,
			"Commit messages must be descriptive and follow conventional commits format",
			"NEVER force push to shared branches",
			"Create feature branches for all non-trivial changes")
	}

	var customRules string
	form2 := huh.NewForm(
		huh.NewGroup(
			huh.NewText().
				Title("Custom Rules").
				Description("Enter any additional guardrails (one per line, or 'none')").
				Value(&customRules),
		),
	)

	if err := form2.WithTheme(huh.ThemeCatppuccin()).Run(); err != nil {
		fmt.Println("Error running guards wizard:", err)
		os.Exit(1)
	}

	customRules = strings.TrimSpace(customRules)
	if customRules != "" && customRules != "none" {
		guards.WriteString("## Custom Rules\n")
		for _, line := range strings.Split(customRules, "\n") {
			line = strings.TrimSpace(line)
			if line != "" {
				fmt.Fprintf(&guards, "- %s\n", line)
				guardrailList = append(guardrailList, line)
			}
		}
	}

	guardsFile := filepath.Join(owlDir, "GUARDS.md")
	if err := os.WriteFile(guardsFile, []byte(guards.String()), 0644); err != nil {
		fmt.Println("Error writing GUARDS.md:", err)
		os.Exit(1)
	}

	var projectCfg struct {
		Version    string   `json:"version"`
		CreatedAt  string   `json:"created_at"`
		Context    string   `json:"context"`
		Guardrails []string `json:"guardrails"`
	}

	b, err := os.ReadFile(projectFile)
	if err != nil {
		fmt.Println("Error reading project.json:", err)
		os.Exit(1)
	}
	if err := json.Unmarshal(b, &projectCfg); err != nil {
		fmt.Println("Error parsing project.json:", err)
		os.Exit(1)
	}
	projectCfg.Guardrails = guardrailList

	b, err = json.MarshalIndent(projectCfg, "", "  ")
	if err != nil {
		fmt.Println("Error marshaling project.json:", err)
		os.Exit(1)
	}
	if err := os.WriteFile(projectFile, b, 0644); err != nil {
		fmt.Println("Error writing project.json:", err)
		os.Exit(1)
	}

	fmt.Printf("\n✓ Guardrails saved to %s and %s\n", projectFile, guardsFile)
}

var templatesCmd = &cobra.Command{
	Use:   "templates",
	Short: "Manage project-level agent templates",
}

var templatesListCmd = &cobra.Command{
	Use:   "list",
	Short: "List available project templates",
	Run:   runTemplatesList,
}

func runTemplatesList(cmd *cobra.Command, args []string) {
	owlDir := ".owl"
	templatesDir := filepath.Join(owlDir, "templates")

	if _, err := os.Stat(filepath.Join(owlDir, "project.json")); os.IsNotExist(err) {
		fmt.Println("Error: Owl project not initialized. Run 'owl project init' first.")
		os.Exit(1)
	}

	entries, err := os.ReadDir(templatesDir)
	if err != nil {
		if os.IsNotExist(err) {
			fmt.Println("No templates directory found.")
			fmt.Println("Create one with: owl project templates create <name>")
			return
		}
		fmt.Println("Error reading templates:", err)
		os.Exit(1)
	}

	tw := tabwriter.NewWriter(os.Stdout, 0, 0, 2, ' ', 0)
	if _, err := fmt.Fprintln(tw, "NAME\tDESCRIPTION"); err != nil {
		fmt.Println("Error writing output:", err)
		os.Exit(1)
	}

	found := false
	for _, entry := range entries {
		if !entry.IsDir() && strings.HasSuffix(entry.Name(), ".json") {
			name := strings.TrimSuffix(entry.Name(), ".json")
			if _, err := fmt.Fprintf(tw, "%s\t\n", name); err != nil {
				fmt.Println("Error writing output:", err)
				os.Exit(1)
			}
			found = true
		}
	}
	if err := tw.Flush(); err != nil {
		fmt.Println("Error writing output:", err)
		os.Exit(1)
	}

	if !found {
		fmt.Println("No templates found.")
		fmt.Println("\nCreate one with: owl project templates create <name>")
	}
}

var templatesCreateCmd = &cobra.Command{
	Use:   "create <name>",
	Short: "Create a new project template",
	Args:  cobra.ExactArgs(1),
	Run:   runTemplatesCreate,
}

func runTemplatesCreate(cmd *cobra.Command, args []string) {
	owlDir := ".owl"
	templatesDir := filepath.Join(owlDir, "templates")
	name := args[0]
	templateFile := filepath.Join(templatesDir, name+".json")

	if _, err := os.Stat(filepath.Join(owlDir, "project.json")); os.IsNotExist(err) {
		fmt.Println("Error: Owl project not initialized. Run 'owl project init' first.")
		os.Exit(1)
	}

	if _, err := os.Stat(templateFile); err == nil {
		fmt.Printf("Error: Template '%s' already exists.\n", name)
		os.Exit(1)
	}

	var tmplName, tmplDescription, tmplSystemPrompt, tmplModel string
	var tmplThinking bool
	var tmplEffort string

	form := huh.NewForm(
		huh.NewGroup(
			huh.NewInput().
				Title("Template Name").
				Description("Internal name for this template").
				Value(&tmplName),
		),
		huh.NewGroup(
			huh.NewInput().
				Title("Description").
				Description("Brief description of what this template is for").
				Value(&tmplDescription),
		),
		huh.NewGroup(
			huh.NewText().
				Title("System Prompt").
				Description("Base instructions for agents using this template").
				Value(&tmplSystemPrompt),
		),
		huh.NewGroup(
			huh.NewInput().
				Title("Default Model").
				Description("Model to use (e.g. anthropic/claude-sonnet-4-6), leave empty for project default").
				Value(&tmplModel),
		),
		huh.NewGroup(
			huh.NewConfirm().
				Title("Extended Thinking").
				Description("Enable extended thinking mode by default?").
				Value(&tmplThinking),
		),
		huh.NewGroup(
			huh.NewSelect[string]().
				Title("Effort Level").
				Description("Default reasoning effort").
				Options(
					huh.NewOption("low", "low"),
					huh.NewOption("medium", "medium"),
					huh.NewOption("high", "high"),
					huh.NewOption("none", ""),
				).
				Value(&tmplEffort),
		),
	)

	if err := form.WithTheme(huh.ThemeCatppuccin()).Run(); err != nil {
		fmt.Println("Error running template wizard:", err)
		os.Exit(1)
	}

	if tmplName == "" {
		tmplName = name
	}

	templateContent := fmt.Sprintf(`{
  "name": %q,
  "description": %q,
  "system_prompt": %q,
  "model": %q,
  "thinking": %t,
  "effort": %q
}
`, tmplName, tmplDescription, tmplSystemPrompt, tmplModel, tmplThinking, tmplEffort)

	if err := os.WriteFile(templateFile, []byte(templateContent), 0644); err != nil {
		fmt.Println("Error creating template:", err)
		os.Exit(1)
	}

	fmt.Printf("✓ Template '%s' created at %s\n", name, templateFile)
}

var templatesDeleteCmd = &cobra.Command{
	Use:   "delete <name>",
	Short: "Delete a project template",
	Args:  cobra.ExactArgs(1),
	Run:   runTemplatesDelete,
}

func runTemplatesDelete(cmd *cobra.Command, args []string) {
	owlDir := ".owl"
	templatesDir := filepath.Join(owlDir, "templates")
	name := args[0]
	templateFile := filepath.Join(templatesDir, name+".json")

	if _, err := os.Stat(filepath.Join(owlDir, "project.json")); os.IsNotExist(err) {
		fmt.Println("Error: Owl project not initialized. Run 'owl project init' first.")
		os.Exit(1)
	}

	if _, err := os.Stat(templateFile); os.IsNotExist(err) {
		fmt.Printf("Error: Template '%s' does not exist.\n", name)
		os.Exit(1)
	}

	if err := os.Remove(templateFile); err != nil {
		fmt.Println("Error deleting template:", err)
		os.Exit(1)
	}

	fmt.Printf("✓ Template '%s' deleted.\n", name)
}

func init() {
	projectCmd.AddCommand(initCmd)
	projectCmd.AddCommand(projectAgentsCmd)
	projectCmd.AddCommand(guardsCmd)
	projectCmd.AddCommand(templatesCmd)
	templatesCmd.AddCommand(templatesListCmd)
	templatesCmd.AddCommand(templatesCreateCmd)
	templatesCmd.AddCommand(templatesDeleteCmd)
	rootCmd.AddCommand(projectCmd)
}
